Add docker to dev images

diff --git a/src/main/debian/Dockerfile.dev b/src/main/debian/Dockerfile.dev
--- a/src/main/debian/Dockerfile.dev
+++ b/src/main/debian/Dockerfile.dev
@@ -32,6 +32,24 @@ RUN apt-get update \
     && rm -rf .git \
   )
 
+ENV DOCKER_CHANNEL="stable" \
+    DOCKER_VERSION="17.03.2-ce"
+RUN set -ex; \
+    dockerArch='x86_64'; \
+    if ! curl -fL -o docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
+        echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
+        exit 1; \
+    fi; \
+    \
+    tar --extract \
+        --file docker.tgz \
+        --strip-components 1 \
+        --directory /usr/local/bin/ \
+    ; \
+    rm docker.tgz; \
+    dockerd -v; \
+    docker -v
+
 COPY diff-so-fancy/diff-* todo.txt/todo.sh /usr/local/bin/
 COPY my_configs.vim /usr/local/vim_runtime/
 COPY *.aliases.bash /usr/local/bash-it/aliases/enabled/
